version: '3'

services:
  site:
    build:
      context: .
    working_dir: /site
    ports:
      - "8080:8080"
      - "9999:9999"
    volumes:
      - ./:/site
      - /site/node_modules
    ulimits:
      nofile:
        soft: 999999
        hard: 999999
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data:

# vim:set ts=2 sw=2 smarttab:
